title: Event Analysis Tool
description: This project, made for the Social Graphs course at DTU, seeks to build a set of tools that facilitate the network analysis and sentiment analysis of any twitter event.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: /Project_Page_SG
markdown: kramdown
