title: The data behind the Church Shooting
description: This project, made for the Social Graphs course at DTU, seeks to explore the data behind the Texas Shooting.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: /Project_Page_SG
