title: Event Analysis Tool
description: This project, made for the Social Graphs and Interaction course at DTU, seeks to build a set of tools that facilitate the network and sentiment analysis of any event through Twitter.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: /Project_Page_SG
markdown: kramdown
